### PR TITLE
adds thumbnail dir

### PR DESCRIPTION
**Pull request by Mearman**
check I haven't made any silly mistakes again 😉

### CODE REVIEW

**Comment by NotExpectedYet** [comment]
I've changes the route now man to it's own images folder. 

Means I can branch off the client later on in the dev cycle and keep the images folder. It's now 

/images 

you need to mount

**Comment by Mearman** [comment]
can do!

**Comment by NotExpectedYet** [comment]
Ma Man!

**Comment by Mearman** [comment]
@NotExpectedYet sorted

**Comment by NotExpectedYet** [comment]
Man I am sorry I should have been clear bahaha 

`/app/views/images/historyCollection`
becomes...
`/app/images`

I've given the images folder it's own route, as I plan to allow snaps uploading for maintanence and history for finished prints. This keeps it all in one place and won't need updating at a later date to incorporate maint/hist

You can leave the designation images though, suits better than thumbnails :)

**Comment by Mearman** [comment]
-_-

**Comment by Mearman** [comment]
done

**Comment by NotExpectedYet** [comment]
Sweet good for release at end of week hopefully thank you very much

**Pull request merged**
